version: '3.8'
networks:
  kkgo_ets_dev_net:
    driver: bridge

volumes: 
  kkgo_ets_dev_persitance_postgresql:

services:
  ## Persistence layer
  # Database
  database:
    extends:
      file: infra/dev/database/docker-compose.yaml
      service: database
    restart: always