version: '3.8'
networks:
  kkgo_ets_test_net:
    driver: bridge

volumes: 
  kkgo_ets_test_persitance_postgresql:

services:
  ## Persistence layer
  # Database
  database:
    extends:
      file: infra/test/database/docker-compose.yaml
      service: database
    restart: always

  # Service layer
  ## Expense tracking
  expense_tracking:
    extends:
      file: infra/test/expense-tracking/docker-compose.yaml
      service: expense_tracking
    restart: always
    depends_on:
      - database