name: KKGo-assessment-cicd

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ==============
  # CI task
  # ==============

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go get ./app

      - name: Run unit test
        run: go test -v -tags unit ./...

  system-integration-test:
    name: System integration test
    runs-on: ubuntu-latest
    # needs: unit-test

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DOMAIN: "kkgo_test.com"
          envkey_IMAGE_NAME: "kkgo"
          envkey_VERSION: "1.0.0"
          envkey_PORT: "2565"
          envkey_DB_DATABASE: "expense_db"
          envkey_DB_USER: "admin_test"
          envkey_DB_PASSWORD: "418fec5f0f023b7a3f5766e8202f8e1c"
          envkey_DB_PORT: "5432"
          envkey_DB_URL: "postgresql://admin_test:418fec5f0f023b7a3f5766e8202f8e1c@database.kkgo_test.com:5432/expense_db?sslmode=disable"

      - name: Integration test inside Docker-compose
        run: docker compose -f docker-compose.test.yaml -p kkgo-ets-test up --build --abort-on-container-exit --exit-code-from expense_tracking
        continue-on-error: true

      - name: Integration test inside Docker-compose cleanup
        run: docker compose -f docker-compose.test.yaml -p kkgo-ets-test down

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    # needs: system-integration-test

    steps:
      - uses: actions/checkout@v3

      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DOMAIN: "kkgo_test.com"
          envkey_IMAGE_NAME: "ghcr.io/rtae/assessment"
          envkey_VERSION: ${{ env.GITHUB_SHA }}
          envkey_PORT: "2565"
          envkey_DB_DATABASE: "expense_db"
          envkey_DB_USER: "admin_test"
          envkey_DB_PASSWORD: "418fec5f0f023b7a3f5766e8202f8e1c"
          envkey_DB_PORT: "5432"
          envkey_DB_URL: "postgresql://admin_test:418fec5f0f023b7a3f5766e8202f8e1c@database.kkgo_test.com:5432/expense_db?sslmode=disable"

      - name: Build image
        run: docker compose -f docker-compose.yaml -p kkgo-ets-prod build

      - name: Login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/rtae/assessment:${{ env.GITHUB_SHA }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          file: infra/prod/expense-tracking/build-image/Dockerfile

      - name: Image digest
        run: echo ghcr.io/rtae/assessment:${{ env.GITHUB_SHA }}
